---
bigip_server_address: 192.168.2.245
bigip_server_user: admin
bigip_server_password: P@ssw0rdDev

# loyalty
bigip_loyalty_front_pool_name: loyalty-front
bigip_loyalty_front_pool_lb: least_connection_member
bigip_loyalty_back_pool_name: loyalty-back
bigip_loyalty_back_pool_lb: round_robin

bigip_loyalty_front_address: 192.168.2.51
bigip_loyalty_front_port: 8081
bigip_loyalty_back_address: 192.168.2.51
bigip_loyalty_back_port: 8082
bigip_loyalty_admin_address: 192.168.2.51
bigip_loyalty_admin_port: 8083
bigip_loyalty_report_address: 192.168.2.51
bigip_loyalty_report_port: 8084

# payment
bigip_loyalty_wallet_address:
bigip_loyalty_wallet_port:
bigip_loyalty_tokenization_address:
bigip_loyalty_tokenization_port:
bigip_loyalty_jpos_address:
bigip_loyalty_jpos_port:


# fintech
