---
- hosts: ansible
  gather_facts: True
  vars_prompt:
    - name: "bigip_pool_name"
      prompt: "your pool name?"
    - name: "bigip_pool_member_address"
      prompt: "your pool member address?"
    - name: "bigip_pool_member_port"
      prompt: "your pool member port?"
  roles:
    - role: bigip_pool/remove_member
