---
  - name: install f5 sdk
    pip: name=f5-sdk

  - name: install bigsuds
    pip: name=bigsuds

  - name: create bigip pool
    bigip_pool:
      server: "{{bigip_server_address}}"
      user: "{{bigip_server_user}}"
      password: "{{bigip_server_password}}"
      state: present
      name: "{{bigip_pool_name}}"
      lb_method: "{{bigip_lb_method}}"
      validate_certs: false
    tags: bigip_create_pool
