---
  - name: create bigip pool
    bigip_pool:
      server: "{{bigip_server_address}}"
      user: "{{bigip_server_user}}"
      password: "{{bigip_server_password}}"
      state: present
      name: "{{bigip_pool_name}}"
      partition: "{{bigip_partition}}"
      lb_method: "{{bigip_lb_method}}"
    tags: bigip_create_pool
